apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  # Base email app password for Gmail SMTP (ritishhire179@gmail.com)
  email-password: dysjjqjsttwwwbya
