apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopwave
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Ritishhire/Shopwave-Microservices-GitOps.git
    targetRevision: main
    path: helm/shopwave

  destination:
    server: https://kubernetes.default.svc
    namespace: shopwave

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true