apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
  annotations:
    # ─── ARGO CD IMAGE UPDATER CONFIGURATION ──────────────────────
    # Enable image updater tracking for frontend container images
    argocd-image-updater.argoproj.io/image-list: frontend=docker.io/ritishhire/ecommerce-frontend
    argocd-image-updater.argoproj.io/frontend.update-strategy: semver
    # Write back updates by committing directly to the git repository
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    # Target Kustomize so it updates the image block in kustomization.yaml
    argocd-image-updater.argoproj.io/write-back-target: kustomization

    # ─── ARGO CD NOTIFICATIONS CONFIGURATION ──────────────────────
    # Send email alerts to ritishhire179@gmail.com
    notifications.argoproj.io/subscribe.on-sync-succeeded.email: ritishhire179@gmail.com
    notifications.argoproj.io/subscribe.on-sync-failed.email: ritishhire179@gmail.com
    notifications.argoproj.io/subscribe.on-health-degraded.email: ritishhire179@gmail.com
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ritishhire/Shopwave-CloudNativeApplication-GitOps.git'
    targetRevision: main
    path: k8s/frontend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
