apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopwave
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: shopwave
    app.kubernetes.io/managed-by: argocd
  annotations:
    # ── NOTIFICATIONS ANNOTATIONS ─────────────────────────────
    # Triggers an email to your address when events happen
    notifications.argoproj.io/subscribe.on-sync-succeeded.email: ritishhire179@gmail.com
    notifications.argoproj.io/subscribe.on-sync-failed.email: ritishhire179@gmail.com
    notifications.argoproj.io/subscribe.on-health-degraded.email: ritishhire179@gmail.com

spec:
  project: default

  source:
    # Points to your Helm Chart
    repoURL: https://github.com/Ritishhire/Shopwave-Microservices-GitOps.git
    targetRevision: main
    path: helm/shopwave
    helm:
      releaseName: shopwave

  destination:
    server: https://kubernetes.default.svc
    namespace: shopwave

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
