global:
  namespace: shopwave

backend:
  image:
    repository: 295435084247.dkr.ecr.ap-south-1.amazonaws.com/shopwave-backend
    tag: v1.0.6
    pullPolicy: Always
  replicas: 2
  port: 5000
  nodeEnv: production
  jwtExpire: 7d
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  probes:
    startup:
      initialDelaySeconds: 10
      failureThreshold: 30
      periodSeconds: 5
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
      successThreshold: 2
    liveness:
      initialDelaySeconds: 20
      periodSeconds: 20
      timeoutSeconds: 3
      failureThreshold: 3
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    cpuUtilization: 70
    memoryUtilization: 80
