apiVersion: v2
name: shopwave
description: ShopWave — full-stack e-commerce application (MongoDB + Node.js API + React/Nginx)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ecommerce
  - nodejs
  - mongodb
  - react
maintainers:
  - name: ritishhire
home: https://github.com/ritishhire
