global:
  namespace: shopwave

frontend:
  image:
    repository: 295435084247.dkr.ecr.ap-south-1.amazonaws.com/shopwave-frontend
    tag: v1.0.6
    pullPolicy: Always
  replicas: 2
  port: 80
  nodePort: 30080
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
  probes:
    startup:
      initialDelaySeconds: 5
      failureThreshold: 18
      periodSeconds: 5
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
      successThreshold: 2
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 3
      failureThreshold: 3
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    cpuUtilization: 70
    memoryUtilization: 80
